package com.xworkz.productMusicInsDTO;

public class ProductTester {
	public static void main(String[] args) {
		
		ProductDTO product=new ProductDTO();
		ProductDTO product1=new ProductDTO();
		ProductDTO product2=new ProductDTO();
		ProductDTO product3=new ProductDTO();
		
		product.setSinger("ShreyaGhoshal");
		System.out.println(product.getSinger());
		product.setArt(true);
		System.out.println(product.isArt());
		product.setBlack("HighPitch");
		System.out.println(product.getBlack());
		product.setHabbit(true);
		System.out.println(product.isHabbit());
		product.setOvertone("unique");
		System.out.println(product.getOvertone());
		product.setPitch("C");
		System.out.println(product.getPitch());
		product.setAmplitude("softSound");
		System.out.println(product.getAmplitude());
		product.setDuration("long");
		System.out.println(product.getDuration());
		product.setMonophony("soloVoice");
		System.out.println(product.getMonophony());
		product.setHomophony("band");
		System.out.println(product.getHomophony());
		product.setPolyphony("independentVoices");
		System.out.println(product.getPolyphony());
		product.setTempo("fast");
		System.out.println(product.getTempo());
		product.setArticulation("stressed or smooth");
		System.out.println(product.getArticulation());
		product.setBeat("steady");
		System.out.println(product.getBeat());
		product.setEmotionalResponse("happy");
		System.out.println(product.getEmotionalResponse());
		product.setTimbre("Rough");
		System.out.println(product.getTimbre());
		product.setMajorScale("CMajor");
		System.out.println(product.getMajorScale());
		product.setMinorScale("AMinor");
		System.out.println(product.getMinorScale());
		product.setMajorPentatonic("C");
		System.out.println(product.getMajorPentatonic());
		product.setMinorPentatonic("A");
		System.out.println(product.getMinorPentatonic());
		product1.setDupleMeters("twoBeats");
		System.out.println(product1.getDupleMeters());
		product1.setTripleMeter(3.5);
		System.out.println(product1.getTripleMeter());
		product1.setCompoundMeter(6.8);
		System.out.println(product1.getCompoundMeter());
		product1.setPiano("soft");
		System.out.println(product1.getPiano());
		product2.setForte("loud");
		System.out.println(product1.getForte());
		product2.setMezzoPiano("moderately soft");
		System.out.println(product1.getMezzoPiano());
		product2.setMezzoForte("moderately loud");
		System.out.println(product1.getMezzoForte());
		product2.setCrescendo("gradually increasing volume");
		System.out.println(product1.getCrescendo());
		product2.setDecrescendo("gradually decreasing volume");
		System.out.println(product1.getDecrescendo());
		product2.setLarghissimo("19 beats per minute or less");
		System.out.println(product1.getLarghissimo());
		product1.setGrave("20-40 bpm");
		System.out.println(product1.getGrave());
		product1.setLento("40-45 bpm");
		System.out.println(product1.getLento());
		product1.setLargo("45-50 bpm");
		System.out.println(product1.getLargo());
		product1.setLarghetto("50-55 bpm");
		System.out.println(product1.getLarghetto());
		product1.setAdagio("55-65 bpm");
		System.out.println(product1.getAdagio());
		product1.setAndante("78-83 bpm");
		System.out.println(product1.getAndante());
		product1.setPresto("168-177 bpm");
		System.out.println(product1.getPresto());
		product1.setPrestissimo("178 bpm and aboce");
		System.out.println(product1.getPrestissimo());
		product1.setAllegrissimo("150-167  bpm");
		System.out.println(product1.getAllegrissimo());
		product1.setVivace("132-140 bpm");
		System.out.println(product1.getVivace());
		product1.setModerato("86-97 bpm");
		System.out.println(product1.getModerato());
		product1.setMarciaModerato("83-85 bpm");
		System.out.println(product1.getMarciaModerato());
		product1.setRecordStudio("AJ studio");
		System.out.println(product1.getRecordStudio());
		product3.setAmplitude("loud");
		System.out.println(product3.getAmplitude());
		product3.setBeat("fast");
		System.out.println(product3.getBeat());
		product3.setForte("loudness");
		System.out.println(product3.getForte());
		product3.setHabbit(true);
		System.out.println(product3.isHabbit());
	    product3.setPulse("steady beat");
	    System.out.println(product3.getPulse());
		product3.setPower(true);
		System.out.println(product3.isPower());
		product3.setHarmony("chords");
		System.out.println(product3.getHarmony());
		product3.setLove(true);
		System.out.println(product3.isLove());
		product3.setPriceOfFlute(5050.0);
		System.out.println(product3.getPriceOfFlute());
		product3.setNoisy(false);
		System.out.println(product3.isNoisy());
		product3.setPriceOfClassicalGuitar(12000);
		System.out.println(product3.getPriceOfClassicalGuitar());
		product3.setPassion(true);
		System.out.println(product3.isPassion());
		product3.setPriceOfViolin(30000);
		System.out.println(product3.getPriceOfViolin());
		product3.setSilence(true);
		System.out.println(product3.isSilence());
		product3.setPriceOfWestguitar(35000);
		System.out.println(product3.getPriceOfWestguitar());
		product3.setSpecial(true);
		System.out.println(product3.isSpecial());
		product3.setMeter("fastbeats");
		System.out.println(product3.getMeter());
		product3.setKannadaMusic("bestMusic");
		System.out.println(product3.getKannadaMusic());
		product3.setLife(true);
		System.out.println(product3.isLife());
		product3.setRange("Alto");
		System.out.println(product3.getRange());
		product3.setDuration("Long");
		System.out.println(product3.getDuration());
		product3.setSoundIntensity(45);
		System.out.println(product3.getSoundIntensity());
		product3.setWriter("Ilaiyaraaja");
		System.out.println(product3.getWriter());
		
		
	}

}
